gfs_main:
    resource: "@GFSMainBundle/Resources/config/routing.yml"
    prefix:   /

gf_sstatistiques:
    resource: "@GFSstatistiquesBundle/Resources/config/routing.yml"
    prefix:   /gestionScolarite

